DAB_2_V0.1.ino
BUFFER_MULTIPLIER
LVGL buffer.
RX_PIN
BM83 UART RX.
TX_PIN
BM83 UART TX.
TX_IND
BM83 TX IND.
DAC1
DAC pin for DC_SET_V.
ENC1_ROTARY_PIN_A
Encoder 1 Pin A.
ENC1_ROTARY_PIN_B
Encoder 1 Pin B.
ENC2_ROTARY_PIN_A
Encoder 2 Pin A.
ENC2_ROTARY_PIN_B
Encoder 2 Pin B.
CLICKS_PER_STEP
MIN_POS
Max volume 0 dB.
MAX_POS
Min volume -87 dB.
START_POS
Volume start position.
INCREMENT
Volume increment.
const int mfbPin
BM83 MFB Pin, required for BM83 power on.
Referenced by setup.
ESPRotary r
Encoder 1 instance.
Referenced by enc_get_new_moves, loop.
ESPRotary u
Encoder 2 instance.
Referenced by loop, rotate_u.
BD37544FS bd
Sound processor instance (BD37544FS)
Referenced by rotate_u.
MCP23017 mcp1
MCP1 (Display board)
Referenced by encoder_read, loop, setup.
MCP23017 mcp2
MCP2 (MCU board)
Referenced by setup.
TaskHandle_t Task1
Task handle.
Referenced by setup.
TaskHandle_t Task2
Task handle.
lv_group_t* g
lv_indev_t* encoder_indev
lv_obj_t* tabview
Referenced by read_inputs.
lv_obj_t* tab1
lv_obj_t* tab2
lv_obj_t* tab3
lv_obj_t* tab4
lv_obj_t* gauge1
lv_obj_t* led1
lv_obj_t* btn
lv_obj_t* btn1
lv_obj_t* btn2
lv_obj_t* btn3
lv_obj_t* sw1
lv_obj_t* sw2
lv_obj_t* sw3
lv_obj_t* cont
lv_obj_t* cont2
lv_obj_t* cont3
lv_obj_t* bar1
lv_obj_t* lmeter
lv_obj_t* lmeter2
lv_obj_t* label
lv_obj_t* spinbox
lv_obj_t* slider_label
lv_obj_t* slider_label2
lv_obj_t* slider_label3
lv_obj_t* slider_label4
lv_obj_t* slider_label5
uint8_t conf
Referenced by loop, read_inputs.
int i
Referenced by read_inputs.
int vol
int encoderLastValue
Referenced by enc_get_new_moves.
int k
Referenced by rotate_u.
TFT_eSPI tft
Referenced by my_disp_flush, setup.
lv_disp_buf_t disp_buf
lv_color_t buf_1[LV_HOR_RES_MAX *BUFFER_MULTIPLIER][LV_HOR_RES_MAX *BUFFER_MULTIPLIER]
lv_color_t buf_2[LV_HOR_RES_MAX *BUFFER_MULTIPLIER][LV_HOR_RES_MAX *BUFFER_MULTIPLIER]
SoftwareSerial swSerial(RX_PIN, TX_PIN)
Software serial instance (BM83)
Referenced by setup.
BM83 bm83(swSerial, TX_IND)
BM83 instance (BM83)
Referenced by read_inputs.
PCA9634 ledDriver(0x15, 4)
Led driver instance (PCA9634)
Referenced by setup.
void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
References tft.
void setup()
References DAC1, ledDriver, mcp1, mcp2, mfbPin, read_inputs, swSerial, Task1, tft.
void loop()
References conf, mcp1, r, u.
void read_inputs(void *parameter)
References bm83, conf, i, tabview.
Referenced by setup.
static void event_bm83setup(lv_obj_t *obj, lv_event_t event)
static void event_bm83pair(lv_obj_t *obj, lv_event_t event)
static void event_soundsetup(lv_obj_t *obj, lv_event_t event)
static void event_sw1(lv_obj_t *obj, lv_event_t event)
void rotate_r(ESPRotary &r)
void showDirection_r(ESPRotary &r)
void rotate_u(ESPRotary &u)
References bd, k, u.
void showDirection_u(ESPRotary &u)
bool encoder_read(lv_indev_drv_t *drv, lv_indev_data_t *data)
References enc_get_new_moves, mcp1.
int enc_get_new_moves()
References encoderLastValue, r.
Referenced by encoder_read.
static void slider_event_cb_ingain(lv_obj_t *slider, lv_event_t event)
static void slider_event_cb_fade1(lv_obj_t *slider, lv_event_t event)
static void slider_event_fade2(lv_obj_t *slider, lv_event_t event)
static void slider_event_cb_bass(lv_obj_t *slider, lv_event_t event)
static void slider_event_mid(lv_obj_t *slider, lv_event_t event)
static void slider_event_treb(lv_obj_t *slider, lv_event_t event)